### ISSUE TITLE
As a professor I want to create a new homework so that my students can practice the class contents.

### ISSUE THREAD

**Issue by victor-sobreira** [ufu-mc-bsi/zenhubtest#11]
### Card (More detailed description)

As a professor I want to create a new homework activity so that my students can practice the class contents.

### Acceptance Criteria:
  - [ ] I can register the problem
  - [ ] I can register the tasks and/or questions
  - [ ] I can send for all the students
  - [ ] I can input the grade
  - [ ] I can receive students solutions

### Tasks:
  - [ ] Task 1
  - [ ] Task 2
  - [ ] Task 3
